# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QDial, QFrame,
    QGraphicsView, QHBoxLayout, QLabel, QMainWindow,
    QPlainTextEdit, QPushButton, QSizePolicy, QSlider,
    QSpinBox, QStatusBar, QVBoxLayout, QWidget)

from pyqtgraph import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(933, 676)
        MainWindow.setMinimumSize(QSize(300, 200))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(78, 143, 173, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush)
        brush2 = QBrush(QColor(85, 170, 0, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush2)
        brush3 = QBrush(QColor(0, 255, 255, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush3)
        brush4 = QBrush(QColor(0, 0, 0, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush4)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush4)
        brush5 = QBrush(QColor(35, 35, 35, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush5)
        brush6 = QBrush(QColor(27, 27, 27, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush6)
        brush7 = QBrush(QColor(85, 170, 255, 255))
        brush7.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush7)
        brush8 = QBrush(QColor(38, 118, 154, 255))
        brush8.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush8)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.HighlightedText, brush4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush2)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush3)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush5)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush7)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush8)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.HighlightedText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush6)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush6)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush7)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText, brush4)
        MainWindow.setPalette(palette)
        MainWindow.setAcceptDrops(True)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setAutoFillBackground(True)
        self.inputFrame = QFrame(self.centralwidget)
        self.inputFrame.setObjectName(u"inputFrame")
        self.inputFrame.setGeometry(QRect(10, 10, 351, 291))
        self.inputFrame.setAcceptDrops(True)
        self.inputFrame.setAutoFillBackground(True)
        self.inputFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.inputFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout = QVBoxLayout(self.inputFrame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.label_3 = QLabel(self.inputFrame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setMaximumSize(QSize(16777215, 20))
        palette1 = QPalette()
        self.label_3.setPalette(palette1)
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)

        self.verticalLayout.addWidget(self.label_3, 0, Qt.AlignmentFlag.AlignHCenter)

        self.fileInputFrame = QFrame(self.inputFrame)
        self.fileInputFrame.setObjectName(u"fileInputFrame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileInputFrame.sizePolicy().hasHeightForWidth())
        self.fileInputFrame.setSizePolicy(sizePolicy)
        self.fileInputFrame.setMinimumSize(QSize(191, 51))
        self.fileInputFrame.setMaximumSize(QSize(500, 40))
        self.fileInputFrame.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.fileInputFrame.setFrameShape(QFrame.Shape.NoFrame)
        self.fileInputFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self.fileInputFrame)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.inputFileDisplay = QPlainTextEdit(self.fileInputFrame)
        self.inputFileDisplay.setObjectName(u"inputFileDisplay")
        self.inputFileDisplay.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.inputFileDisplay.sizePolicy().hasHeightForWidth())
        self.inputFileDisplay.setSizePolicy(sizePolicy1)
        self.inputFileDisplay.setMinimumSize(QSize(92, 31))
        self.inputFileDisplay.setMaximumSize(QSize(16777215, 31))
        self.inputFileDisplay.setStyleSheet(u"background-color: rgb(35, 35, 35);")
        self.inputFileDisplay.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.inputFileDisplay.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.inputFileDisplay.setUndoRedoEnabled(False)
        self.inputFileDisplay.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.inputFileDisplay.setReadOnly(True)
        self.inputFileDisplay.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.inputFileDisplay.setBackgroundVisible(False)
        self.inputFileDisplay.setCenterOnScroll(False)

        self.horizontalLayout.addWidget(self.inputFileDisplay)

        self.inputFileButton = QPushButton(self.fileInputFrame)
        self.inputFileButton.setObjectName(u"inputFileButton")
        self.inputFileButton.setMinimumSize(QSize(75, 24))
        self.inputFileButton.setMaximumSize(QSize(89, 24))
        self.inputFileButton.setStyleSheet(u"QPushButton { padding-left: 0px; padding-right: 0px; background-color: rgb(78, 143, 173); }\n"
"\n"
"QPushButton:hover { background-color: rgb(87, 161, 193) }\n"
"\n"
"QPushButton:pressed { background-color: rgb(62, 115, 138);}")

        self.horizontalLayout.addWidget(self.inputFileButton)


        self.verticalLayout.addWidget(self.fileInputFrame, 0, Qt.AlignmentFlag.AlignHCenter)

        self.InputPeekWidget = PlotWidget(self.inputFrame)
        self.InputPeekWidget.setObjectName(u"InputPeekWidget")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.InputPeekWidget.sizePolicy().hasHeightForWidth())
        self.InputPeekWidget.setSizePolicy(sizePolicy2)
        self.InputPeekWidget.setMinimumSize(QSize(256, 117))
        self.InputPeekWidget.setMaximumSize(QSize(99999, 117))
        self.InputPeekWidget.setInteractive(False)

        self.verticalLayout.addWidget(self.InputPeekWidget, 0, Qt.AlignmentFlag.AlignHCenter)

        self.inputPlaybackFrame = QFrame(self.inputFrame)
        self.inputPlaybackFrame.setObjectName(u"inputPlaybackFrame")
        self.inputPlaybackFrame.setMaximumSize(QSize(16777215, 45))
        self.inputPlaybackFrame.setAutoFillBackground(False)
        self.inputPlaybackFrame.setStyleSheet(u"QPushButton { padding-left: 0px; padding-right: 0px; background-color: rgb(78, 143, 173); height: 30px;}\n"
"\n"
"QPushButton:hover { background-color: rgb(87, 161, 193) }\n"
"\n"
"QPushButton:pressed { background-color: rgb(62, 115, 138);}")
        self.inputPlaybackFrame.setFrameShape(QFrame.Shape.NoFrame)
        self.inputPlaybackFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.inputPlaybackFrame)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.inputRestartButton = QPushButton(self.inputPlaybackFrame)
        self.inputRestartButton.setObjectName(u"inputRestartButton")
        self.inputRestartButton.setEnabled(True)
        self.inputRestartButton.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaSkipBackward))
        self.inputRestartButton.setIcon(icon)
        self.inputRestartButton.setAutoRepeatDelay(300)

        self.horizontalLayout_4.addWidget(self.inputRestartButton)

        self.inputPlayButton = QPushButton(self.inputPlaybackFrame)
        self.inputPlayButton.setObjectName(u"inputPlayButton")
        self.inputPlayButton.setEnabled(True)
        self.inputPlayButton.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.inputPlayButton.setAutoFillBackground(False)
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaPlaybackStart))
        self.inputPlayButton.setIcon(icon1)
        self.inputPlayButton.setAutoRepeatDelay(300)

        self.horizontalLayout_4.addWidget(self.inputPlayButton)

        self.inputStopButton = QPushButton(self.inputPlaybackFrame)
        self.inputStopButton.setObjectName(u"inputStopButton")
        self.inputStopButton.setEnabled(True)
        self.inputStopButton.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaPlaybackStop))
        self.inputStopButton.setIcon(icon2)
        self.inputStopButton.setAutoRepeatDelay(300)

        self.horizontalLayout_4.addWidget(self.inputStopButton)


        self.verticalLayout.addWidget(self.inputPlaybackFrame)

        self.IRFrame = QFrame(self.centralwidget)
        self.IRFrame.setObjectName(u"IRFrame")
        self.IRFrame.setGeometry(QRect(10, 330, 351, 291))
        self.IRFrame.setAcceptDrops(True)
        self.IRFrame.setAutoFillBackground(True)
        self.IRFrame.setStyleSheet(u"")
        self.IRFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.IRFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.IRFrame)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label_5 = QLabel(self.IRFrame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMaximumSize(QSize(16777215, 20))
        self.label_5.setFont(font)

        self.verticalLayout_2.addWidget(self.label_5, 0, Qt.AlignmentFlag.AlignHCenter)

        self.IRInputFrame = QFrame(self.IRFrame)
        self.IRInputFrame.setObjectName(u"IRInputFrame")
        sizePolicy.setHeightForWidth(self.IRInputFrame.sizePolicy().hasHeightForWidth())
        self.IRInputFrame.setSizePolicy(sizePolicy)
        self.IRInputFrame.setMinimumSize(QSize(191, 51))
        self.IRInputFrame.setMaximumSize(QSize(500, 40))
        self.IRInputFrame.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.IRInputFrame.setFrameShape(QFrame.Shape.NoFrame)
        self.IRInputFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.IRInputFrame)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.IRFileDisplay = QPlainTextEdit(self.IRInputFrame)
        self.IRFileDisplay.setObjectName(u"IRFileDisplay")
        self.IRFileDisplay.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.IRFileDisplay.sizePolicy().hasHeightForWidth())
        self.IRFileDisplay.setSizePolicy(sizePolicy1)
        self.IRFileDisplay.setMinimumSize(QSize(92, 31))
        self.IRFileDisplay.setMaximumSize(QSize(16777215, 31))
        self.IRFileDisplay.setStyleSheet(u"background-color: rgb(35, 35, 35);")
        self.IRFileDisplay.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.IRFileDisplay.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.IRFileDisplay.setUndoRedoEnabled(False)
        self.IRFileDisplay.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.IRFileDisplay.setReadOnly(True)
        self.IRFileDisplay.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.IRFileDisplay.setCenterOnScroll(False)

        self.horizontalLayout_2.addWidget(self.IRFileDisplay)

        self.IRFileButton = QPushButton(self.IRInputFrame)
        self.IRFileButton.setObjectName(u"IRFileButton")
        self.IRFileButton.setMinimumSize(QSize(75, 24))
        self.IRFileButton.setMaximumSize(QSize(89, 24))
        self.IRFileButton.setToolTipDuration(-1)
        self.IRFileButton.setStyleSheet(u"QPushButton { padding-left: 0px; padding-right: 0px; background-color: rgb(78, 143, 173); text-color: rgb(12, 12, 13) }\n"
"\n"
"QPushButton:hover { background-color: rgb(87, 161, 193) }\n"
"\n"
"QPushButton:pressed { background-color: rgb(62, 115, 138);}")

        self.horizontalLayout_2.addWidget(self.IRFileButton)


        self.verticalLayout_2.addWidget(self.IRInputFrame, 0, Qt.AlignmentFlag.AlignHCenter)

        self.IRPeekWidget = PlotWidget(self.IRFrame)
        self.IRPeekWidget.setObjectName(u"IRPeekWidget")
        self.IRPeekWidget.setMinimumSize(QSize(256, 117))
        self.IRPeekWidget.setMaximumSize(QSize(16777215, 117))
        self.IRPeekWidget.setInteractive(False)

        self.verticalLayout_2.addWidget(self.IRPeekWidget, 0, Qt.AlignmentFlag.AlignHCenter)

        self.IRPlaybackFrame = QFrame(self.IRFrame)
        self.IRPlaybackFrame.setObjectName(u"IRPlaybackFrame")
        self.IRPlaybackFrame.setMaximumSize(QSize(16777215, 45))
        self.IRPlaybackFrame.setStyleSheet(u"QPushButton { padding-left: 0px; padding-right: 0px; background-color: rgb(78, 143, 173); height: 30px; }\n"
"\n"
"QPushButton:hover { background-color: rgb(87, 161, 193) }\n"
"\n"
"QPushButton:pressed { background-color: rgb(62, 115, 138);}")
        self.IRPlaybackFrame.setFrameShape(QFrame.Shape.NoFrame)
        self.IRPlaybackFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.IRPlaybackFrame)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.IRRestartButton = QPushButton(self.IRPlaybackFrame)
        self.IRRestartButton.setObjectName(u"IRRestartButton")
        self.IRRestartButton.setEnabled(True)
        self.IRRestartButton.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.IRRestartButton.setIcon(icon)
        self.IRRestartButton.setAutoRepeatDelay(300)

        self.horizontalLayout_3.addWidget(self.IRRestartButton)

        self.IRPlayButton = QPushButton(self.IRPlaybackFrame)
        self.IRPlayButton.setObjectName(u"IRPlayButton")
        self.IRPlayButton.setEnabled(True)
        self.IRPlayButton.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.IRPlayButton.setIcon(icon1)
        self.IRPlayButton.setAutoRepeatDelay(300)

        self.horizontalLayout_3.addWidget(self.IRPlayButton)

        self.IRStopButton = QPushButton(self.IRPlaybackFrame)
        self.IRStopButton.setObjectName(u"IRStopButton")
        self.IRStopButton.setEnabled(True)
        font1 = QFont()
        font1.setBold(False)
        font1.setUnderline(False)
        font1.setStrikeOut(False)
        font1.setKerning(True)
        font1.setStyleStrategy(QFont.PreferDefault)
        self.IRStopButton.setFont(font1)
        self.IRStopButton.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.IRStopButton.setAutoFillBackground(False)
        self.IRStopButton.setIcon(icon2)
#if QT_CONFIG(shortcut)
        self.IRStopButton.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.IRStopButton.setAutoRepeatDelay(300)

        self.horizontalLayout_3.addWidget(self.IRStopButton)


        self.verticalLayout_2.addWidget(self.IRPlaybackFrame)

        self.outputFrame = QFrame(self.centralwidget)
        self.outputFrame.setObjectName(u"outputFrame")
        self.outputFrame.setGeometry(QRect(390, 10, 471, 381))
        self.outputFrame.setAutoFillBackground(True)
        self.outputFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.outputFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.outputFrame)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.label_7 = QLabel(self.outputFrame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setFont(font)
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_7)

        self.graphicsView = PlotWidget(self.outputFrame)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setInteractive(False)
        self.graphicsView.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.graphicsView.setCacheMode(QGraphicsView.CacheModeFlag.CacheBackground)

        self.verticalLayout_3.addWidget(self.graphicsView)

        self.outputPlaybackFrame = QFrame(self.outputFrame)
        self.outputPlaybackFrame.setObjectName(u"outputPlaybackFrame")
        self.outputPlaybackFrame.setStyleSheet(u"QPushButton { padding-left: 0px; padding-right: 0px; background-color: rgb(78, 143, 173); }\n"
"\n"
"QPushButton:hover { background-color: rgb(87, 161, 193) }\n"
"\n"
"QPushButton:pressed { background-color: rgb(62, 115, 138);}")
        self.outputPlaybackFrame.setFrameShape(QFrame.Shape.NoFrame)
        self.outputPlaybackFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.outputPlaybackFrame)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.outputRestartButton = QPushButton(self.outputPlaybackFrame)
        self.outputRestartButton.setObjectName(u"outputRestartButton")
        self.outputRestartButton.setEnabled(True)
        self.outputRestartButton.setMinimumSize(QSize(0, 30))
        self.outputRestartButton.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.outputRestartButton.setIcon(icon)
        self.outputRestartButton.setAutoRepeatDelay(300)

        self.horizontalLayout_5.addWidget(self.outputRestartButton)

        self.outputPlayButton = QPushButton(self.outputPlaybackFrame)
        self.outputPlayButton.setObjectName(u"outputPlayButton")
        self.outputPlayButton.setEnabled(True)
        self.outputPlayButton.setMinimumSize(QSize(0, 30))
        self.outputPlayButton.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.outputPlayButton.setIcon(icon1)
        self.outputPlayButton.setAutoRepeatDelay(300)

        self.horizontalLayout_5.addWidget(self.outputPlayButton)

        self.outputStopButton = QPushButton(self.outputPlaybackFrame)
        self.outputStopButton.setObjectName(u"outputStopButton")
        self.outputStopButton.setEnabled(True)
        self.outputStopButton.setMinimumSize(QSize(0, 30))
        self.outputStopButton.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.outputStopButton.setIcon(icon2)
        self.outputStopButton.setAutoRepeatDelay(300)

        self.horizontalLayout_5.addWidget(self.outputStopButton)


        self.verticalLayout_3.addWidget(self.outputPlaybackFrame)

        self.saveButton = QPushButton(self.centralwidget)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(790, 590, 121, 51))
        self.saveButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.saveButton.setStyleSheet(u"QPushButton { padding-left: 0px; padding-right: 0px; background-color: rgb(78, 143, 173); }\n"
"\n"
"QPushButton:hover { background-color: rgb(87, 161, 193) }\n"
"\n"
"QPushButton:pressed { background-color: rgb(62, 115, 138);}")
        self.saveButton.setAutoDefault(True)
        self.clearButton = QPushButton(self.centralwidget)
        self.clearButton.setObjectName(u"clearButton")
        self.clearButton.setEnabled(True)
        self.clearButton.setGeometry(QRect(790, 530, 121, 51))
        self.clearButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.clearButton.setMouseTracking(True)
        self.clearButton.setAcceptDrops(False)
        self.clearButton.setStyleSheet(u"QPushButton { padding-left: 0px; padding-right: 0px; background-color: rgb(78, 143, 173); }\n"
"\n"
"QPushButton:hover { background-color: rgb(87, 161, 193) }\n"
"\n"
"QPushButton:pressed { background-color: rgb(62, 115, 138);}")
        self.clearButton.setCheckable(False)
        self.gainFrame = QFrame(self.centralwidget)
        self.gainFrame.setObjectName(u"gainFrame")
        self.gainFrame.setGeometry(QRect(390, 420, 371, 221))
        self.gainFrame.setAutoFillBackground(True)
        self.gainFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.gainFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_6 = QHBoxLayout(self.gainFrame)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.inputGainFrame = QFrame(self.gainFrame)
        self.inputGainFrame.setObjectName(u"inputGainFrame")
        self.inputGainFrame.setEnabled(True)
        sizePolicy.setHeightForWidth(self.inputGainFrame.sizePolicy().hasHeightForWidth())
        self.inputGainFrame.setSizePolicy(sizePolicy)
        self.inputGainFrame.setMinimumSize(QSize(0, 101))
        self.inputGainFrame.setMaximumSize(QSize(500, 200))
        font2 = QFont()
        font2.setPointSize(9)
        self.inputGainFrame.setFont(font2)
        self.inputGainFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.inputGainFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.inputGainFrame)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.inputGainLabel = QLabel(self.inputGainFrame)
        self.inputGainLabel.setObjectName(u"inputGainLabel")
        font3 = QFont()
        font3.setPointSize(11)
        self.inputGainLabel.setFont(font3)
        self.inputGainLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_4.addWidget(self.inputGainLabel)

        self.inputDial = QDial(self.inputGainFrame)
        self.inputDial.setObjectName(u"inputDial")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.inputDial.sizePolicy().hasHeightForWidth())
        self.inputDial.setSizePolicy(sizePolicy3)
        self.inputDial.setMinimumSize(QSize(80, 65))
        self.inputDial.setMaximumSize(QSize(92, 16777215))
        self.inputDial.setMinimum(-10)
        self.inputDial.setMaximum(10)
        self.inputDial.setValue(0)
        self.inputDial.setSliderPosition(0)
        self.inputDial.setTracking(False)
        self.inputDial.setWrapping(False)
        self.inputDial.setNotchesVisible(True)

        self.verticalLayout_4.addWidget(self.inputDial)

        self.inputSpinBox = QSpinBox(self.inputGainFrame)
        self.inputSpinBox.setObjectName(u"inputSpinBox")
        self.inputSpinBox.setMinimumSize(QSize(71, 31))
        self.inputSpinBox.setMaximumSize(QSize(71, 16777215))
        self.inputSpinBox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.inputSpinBox.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.inputSpinBox.setProperty(u"showGroupSeparator", False)
        self.inputSpinBox.setMinimum(-10)
        self.inputSpinBox.setMaximum(10)

        self.verticalLayout_4.addWidget(self.inputSpinBox, 0, Qt.AlignmentFlag.AlignHCenter)


        self.horizontalLayout_6.addWidget(self.inputGainFrame)

        self.IRGainFrame = QFrame(self.gainFrame)
        self.IRGainFrame.setObjectName(u"IRGainFrame")
        self.IRGainFrame.setEnabled(True)
        sizePolicy.setHeightForWidth(self.IRGainFrame.sizePolicy().hasHeightForWidth())
        self.IRGainFrame.setSizePolicy(sizePolicy)
        self.IRGainFrame.setMinimumSize(QSize(0, 101))
        self.IRGainFrame.setMaximumSize(QSize(500, 200))
        self.IRGainFrame.setFont(font2)
        self.IRGainFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.IRGainFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_6 = QVBoxLayout(self.IRGainFrame)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.IRGainLabel = QLabel(self.IRGainFrame)
        self.IRGainLabel.setObjectName(u"IRGainLabel")
        self.IRGainLabel.setFont(font3)
        self.IRGainLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_6.addWidget(self.IRGainLabel)

        self.IRDial = QDial(self.IRGainFrame)
        self.IRDial.setObjectName(u"IRDial")
        sizePolicy3.setHeightForWidth(self.IRDial.sizePolicy().hasHeightForWidth())
        self.IRDial.setSizePolicy(sizePolicy3)
        self.IRDial.setMinimumSize(QSize(80, 95))
        self.IRDial.setMaximumSize(QSize(92, 16777215))
        self.IRDial.setMinimum(-10)
        self.IRDial.setMaximum(10)
        self.IRDial.setValue(0)
        self.IRDial.setSliderPosition(0)
        self.IRDial.setTracking(False)
        self.IRDial.setWrapping(False)
        self.IRDial.setNotchesVisible(True)

        self.verticalLayout_6.addWidget(self.IRDial, 0, Qt.AlignmentFlag.AlignHCenter)

        self.IRSpinBox = QSpinBox(self.IRGainFrame)
        self.IRSpinBox.setObjectName(u"IRSpinBox")
        self.IRSpinBox.setMinimumSize(QSize(71, 31))
        self.IRSpinBox.setMaximumSize(QSize(71, 16777215))
        self.IRSpinBox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.IRSpinBox.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.IRSpinBox.setProperty(u"showGroupSeparator", False)
        self.IRSpinBox.setMinimum(-10)
        self.IRSpinBox.setMaximum(10)

        self.verticalLayout_6.addWidget(self.IRSpinBox, 0, Qt.AlignmentFlag.AlignHCenter)


        self.horizontalLayout_6.addWidget(self.IRGainFrame)

        self.OutputGainFrame = QFrame(self.gainFrame)
        self.OutputGainFrame.setObjectName(u"OutputGainFrame")
        self.OutputGainFrame.setEnabled(True)
        sizePolicy.setHeightForWidth(self.OutputGainFrame.sizePolicy().hasHeightForWidth())
        self.OutputGainFrame.setSizePolicy(sizePolicy)
        self.OutputGainFrame.setMinimumSize(QSize(0, 101))
        self.OutputGainFrame.setMaximumSize(QSize(112, 200))
        self.OutputGainFrame.setFont(font2)
        self.OutputGainFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.OutputGainFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.OutputGainFrame)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.OutputGainLabel = QLabel(self.OutputGainFrame)
        self.OutputGainLabel.setObjectName(u"OutputGainLabel")
        self.OutputGainLabel.setFont(font3)
        self.OutputGainLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_5.addWidget(self.OutputGainLabel)

        self.OutputDial = QDial(self.OutputGainFrame)
        self.OutputDial.setObjectName(u"OutputDial")
        self.OutputDial.setMinimumSize(QSize(0, 95))
        self.OutputDial.setMaximumSize(QSize(100, 16777215))
        self.OutputDial.setAcceptDrops(False)
        self.OutputDial.setAutoFillBackground(False)
        self.OutputDial.setMinimum(-10)
        self.OutputDial.setMaximum(10)
        self.OutputDial.setSliderPosition(0)
        self.OutputDial.setTracking(False)
        self.OutputDial.setInvertedAppearance(False)
        self.OutputDial.setNotchesVisible(True)

        self.verticalLayout_5.addWidget(self.OutputDial)

        self.OutputSpinBox = QSpinBox(self.OutputGainFrame)
        self.OutputSpinBox.setObjectName(u"OutputSpinBox")
        self.OutputSpinBox.setMinimumSize(QSize(71, 31))
        self.OutputSpinBox.setMaximumSize(QSize(71, 31))
        self.OutputSpinBox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.OutputSpinBox.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.OutputSpinBox.setProperty(u"showGroupSeparator", False)
        self.OutputSpinBox.setMinimum(-10)
        self.OutputSpinBox.setMaximum(10)

        self.verticalLayout_5.addWidget(self.OutputSpinBox, 0, Qt.AlignmentFlag.AlignHCenter)


        self.horizontalLayout_6.addWidget(self.OutputGainFrame)

        self.verticalSlider = QSlider(self.centralwidget)
        self.verticalSlider.setObjectName(u"verticalSlider")
        self.verticalSlider.setGeometry(QRect(890, 40, 20, 311))
        self.verticalSlider.setOrientation(Qt.Orientation.Vertical)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(890, 360, 105, 20))
        self.label_6.setMaximumSize(QSize(16777215, 20))
        self.label_6.setFont(font)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(880, 10, 105, 20))
        self.label_8.setMaximumSize(QSize(16777215, 20))
        self.label_8.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.gainFrame.raise_()
        self.inputFrame.raise_()
        self.IRFrame.raise_()
        self.outputFrame.raise_()
        self.saveButton.raise_()
        self.clearButton.raise_()
        self.verticalSlider.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.inputSpinBox.valueChanged.connect(self.inputDial.setValue)
        self.inputDial.valueChanged.connect(self.inputSpinBox.setValue)
        self.IRSpinBox.valueChanged.connect(self.IRDial.setValue)
        self.IRDial.valueChanged.connect(self.IRSpinBox.setValue)
        self.OutputSpinBox.valueChanged.connect(self.OutputDial.setValue)
        self.OutputDial.valueChanged.connect(self.OutputSpinBox.setValue)

        self.saveButton.setDefault(True)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Audio Convolver", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Input Audio", None))
        self.inputFileDisplay.setPlainText("")
        self.inputFileDisplay.setPlaceholderText(QCoreApplication.translate("MainWindow", u"filename...", None))
#if QT_CONFIG(tooltip)
        self.inputFileButton.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Accepted formats: </p><p>.mp3, .wav, .flac, .aiff, .au, .caf</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.inputFileButton.setText(QCoreApplication.translate("MainWindow", u"Select File...", None))
        self.inputRestartButton.setText("")
        self.inputPlayButton.setText("")
        self.inputStopButton.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Impulse Reponse", None))
        self.IRFileDisplay.setPlainText("")
        self.IRFileDisplay.setPlaceholderText(QCoreApplication.translate("MainWindow", u"filename...", None))
#if QT_CONFIG(tooltip)
        self.IRFileButton.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Accepted formats: </p><p>.mp3, .wav, .flac, .aiff, .au, .caf</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.IRFileButton.setText(QCoreApplication.translate("MainWindow", u"Select File...", None))
        self.IRRestartButton.setText("")
        self.IRPlayButton.setText("")
        self.IRStopButton.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Output Audio", None))
        self.outputRestartButton.setText("")
        self.outputPlayButton.setText("")
        self.outputStopButton.setText("")
        self.saveButton.setText(QCoreApplication.translate("MainWindow", u"Save As...", None))
        self.clearButton.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.inputGainLabel.setText(QCoreApplication.translate("MainWindow", u"Input Gain", None))
        self.inputSpinBox.setSuffix(QCoreApplication.translate("MainWindow", u" dB", None))
        self.IRGainLabel.setText(QCoreApplication.translate("MainWindow", u"IR Gain", None))
        self.IRSpinBox.setSuffix(QCoreApplication.translate("MainWindow", u" dB", None))
        self.OutputGainLabel.setText(QCoreApplication.translate("MainWindow", u"Output Gain", None))
        self.OutputSpinBox.setSuffix(QCoreApplication.translate("MainWindow", u" dB", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Dry", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Wet", None))
    # retranslateUi

